### ISSUE TITLE
Bug: Incorrect 'Failed and Needs Execution' message on proposal card

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/pokemol-web#1783] opened 2022-04-25 19:24 UTC
**Describe the bug**
 Proposal card in Proposal list view displays a failed funding proposal as “Failled and needs execution”

**To Reproduce**
See it live [here](https://app.daohaus.club/dao/0x64/0xcd8fad1a2fc74bce90e9f5fd87164c68ecca9c12/proposals)

1. filter ‘Funding Proposals’

2. navigate to the 2nd page

3. Is not executable when clicked through. Failed because of ‘No’ vote Does not occur when vote is ‘Yes’ but failed because of lack of funds.

**Expected behavior**

Message should just read 'Failed'. 

See the proposal detail page doesn't indicate execution is needed:

proposal detail:
https://app.daohaus.club/dao/0x64/0xcd8fad1a2fc74bce90e9f5fd87164c68ecca9c12/proposals/249

**Screenshots**

![Screenshot from 2022-04-25 13-23-16](https://user-images.githubusercontent.com/6923345/165159468-0c74f1b9-fc99-4862-bc55-7fd94c4d93cc.png)

**Application area**

Where in the app is this happening?
- FrontEnd (please include route/section if possible)

/proposals

https://app.daohaus.club/dao/0x64/0xcd8fad1a2fc74bce90e9f5fd87164c68ecca9c12/proposals/249

**Comment by scottrepreneur** [comment] 2022-05-16 17:18
Is this prior to processing? Not seeing this currently

<img width="1207" alt="Screen Shot 2022-05-16 at 12 18 17" src="https://user-images.githubusercontent.com/1778380/168647956-1905e130-9195-4ac3-aca1-291d36b0c6d1.png">

Might've been fixed with #1784 & #1820

**Comment by plor** [comment] 2022-05-16 17:29
Yeah, that change could have fixed this for sure. I'm just double checking to see if I can reproduce now.

**Comment by plor** [comment] 2022-05-16 18:13
Ok, I was unable to reproduce this, so I'm going to mark this as complete. I think then that it is fixed by #1820

**Closed as completed by plor** 2022-05-16 18:13 UTC
Labels: bug
