### ISSUE TITLE
Bug: Webpage shows "Insufficient Funds" error when create member proposer to a DAO using a custom token who's decimal is not 18

### ISSUE THREAD

**Issue by jerry65536** [odyssy-automaton/pokemol-web#1087] opened 2021-05-09 16:37 UTC
Hi, I have found a issue when create member proposal. Here is the details.

I have created a test DAO on Rinkeby network:
https://app.daohaus.club/dao/0x4/0xda44583fdae5f4601d18f8f7d6198395ad3e89ce/settings

The DAO is using a custom ERC20 token named T1. And this token is set to use 2 decimals. And I have set the proposal deposit of DAO to 0.1 T1.
https://rinkeby.etherscan.io/address/0x21c1abdd8864349d666f8dc404e78637c1c4e3b9#code

Then I switch to another account to add member proposal to this DAO. Here are the steps how the issue happened.

- Step1: If I set Token Tribute to 0, I can create this proposal on the webpage.

- Step2: But if I set Token Tribute to 1 (or any other number bigger than 0), it will always shows **Insignificant Funds**. In fact, my account have 5 T1 token. If I click the button "Max", it can read the balance of T1 token and fill 5 into the input box, this also confirmed that I have 5 T1 token indeed.

  ![image](https://user-images.githubusercontent.com/83581997/117579877-99605400-b127-11eb-8da2-a13c52906ec0.png)

- Step3: I have tried to manually call the contract with etherscan. The arguments is just like the Step1, but change the Token Tribute to 1 (0.01 T1), the call will execute successfully and I can see the proposal I made in the webpage.

We can see the two proposals from Step1 and Step3 here:
https://app.daohaus.club/dao/0x4/0xda44583fdae5f4601d18f8f7d6198395ad3e89ce/proposals

And the tx records are here
https://rinkeby.etherscan.io/tx/0x3c66a7d323cf0e27d4eeb119aaf1490d8a5075e43d336815d25426135f26b67a
https://rinkeby.etherscan.io/tx/0x7a6b153bee9ea2a06a924f5de94d39e65f16c5c661ba24f53a43dce4ea09367b

I think this may be a bug of the webpage. And seems it only happened when we use a token who's decimal is not 18.

**Comment by drop-out-dev** [comment] 2021-06-29 20:38
I'm running into the same issue with a DAO summoned on xDAI.
[The buggy DAO](https://app.daohaus.club/dao/0x64/0xe53b041b47e881435435a12c05e859ddc6565eef
)

The DAO uses USDC, which has 6 decimals. The DAO was summoned with 10 USDC as a proposal deposit, but it seems the UI assumes 18 decimals because the proposal deposit is now 10000000000000 USDC, making it impossible to submit proposals.

**Comment by plor** [comment] 2022-05-25 00:54
I deployed a token with 2 decimals like the one above and was not able to reproduce. This was likely fixed with some other refactors and shouldn't be a problem anymore. Feel free to reach out if this remains an issue.

![Image](https://user-images.githubusercontent.com/408660/170155525-fa02472c-7f4b-494b-8e0e-9c05340a1fc4.png)

**Closed as not planned by plor** 2022-05-25 00:54 UTC
Labels: bug
