### ISSUE TITLE
Tribute token unlock doesn't reset the form error

### ISSUE THREAD

**Issue by jonathanprozzi** [odyssy-automaton/pokemol-web#1735] opened 2022-03-22 15:49 UTC
## What

After unlocking a tribute token and successfully signing the transaction the initial error message doesn't clear, preventing the form submission.

## To Replicate

1. Go to a form with a tribute field in a DAO you haven't approved to spend a token
  - You'll see the **Unlock** button
3. Click **Unlock** and sign transaction
  - After the tx is successful the error message never clears out so the form cannot be submitted
  - 
## Resources

[Initial Discord Message Link](https://discord.com/channels/709210493549674598/908738422666063892/931300830622126080)

**Comment by skuhlmann** [comment] 2022-04-12 23:57
duplicate of
https://github.com/HausDAO/daohaus-app/issues/1765

**Closed as completed by skuhlmann** 2022-04-12 23:57 UTC
Labels: bug, duplicate
